language: generic
sudo: false

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask

env:
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis

matrix:
  fast_finish: true

script:
  - emacs --version
  - make check
